#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pound
Version  : 2.7
Release  : 8
URL      : http://www.apsis.ch/pound/Pound-2.7.tgz
Source0  : http://www.apsis.ch/pound/Pound-2.7.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: Pound-bin
Requires: Pound-data
Requires: Pound-doc
BuildRequires : openssl-dev
Patch1: pound-remove-owner.patch
Patch2: 0001-Pound-Configuration-file-sample.patch

%description
POUND - REVERSE-PROXY AND LOAD-BALANCER
The Pound program is a reverse proxy, load balancer and
HTTPS front-end for Web server(s). Pound was developed
to enable distributing the load among several Web-servers
and to allow for a convenient SSL wrapper for those Web
servers that do not offer it natively. Pound is distributed
under the GPL - no warranty, it's free to use, copy and
give away.

%package bin
Summary: bin components for the Pound package.
Group: Binaries
Requires: Pound-data

%description bin
bin components for the Pound package.


%package data
Summary: data components for the Pound package.
Group: Data

%description data
data components for the Pound package.


%package doc
Summary: doc components for the Pound package.
Group: Documentation

%description doc
doc components for the Pound package.


%prep
%setup -q -n Pound-2.7
%patch1 -p1
%patch2 -p1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
## make_install_append content
install -d -m 755 %{buildroot}/usr/share/defaults/pound/
install -p -D -m 644 etc/pound/pound.cfg %{buildroot}/usr/share/defaults/pound/pound.cfg.sample
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pound
/usr/bin/poundctl

%files data
%defattr(-,root,root,-)
/usr/share/defaults/pound/pound.cfg.sample

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
